In [32]:
import torch
import torch.nn.functional as F

In [33]:
target = torch.FloatTensor([[0.1,0.2,0.3]
                           ,[0.4,0.5,0.6]
                           ,[0.7,0.8,0.9]])

In [34]:
x = torch.rand_like(target)
x.requires_grad = True
x

tensor([[0.6711, 0.2580, 0.5161],
        [0.7701, 0.2759, 0.4597],
        [0.0574, 0.3092, 0.6652]], requires_grad=True)

In [35]:
loss = F.mse_loss(x,target)

In [36]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss>threshold:
    iter_cnt +=1
    loss = F.mse_loss(x,target)
    loss.backward()
    x = x-learning_rate*x.grad
    x.detach_()
    x.requires_grad_(True)
    print("%d-th loss : %.4e" % (iter_cnt,loss))
    print(x)

1-th loss : 1.4356e-01
tensor([[0.5442, 0.2451, 0.4681],
        [0.6879, 0.3257, 0.4909],
        [0.2002, 0.4182, 0.7173]], requires_grad=True)
2-th loss : 8.6845e-02
tensor([[0.4455, 0.2351, 0.4307],
        [0.6239, 0.3644, 0.5152],
        [0.3113, 0.5031, 0.7579]], requires_grad=True)
3-th loss : 5.2536e-02
tensor([[0.3687, 0.2273, 0.4017],
        [0.5742, 0.3945, 0.5340],
        [0.3977, 0.5691, 0.7895]], requires_grad=True)
4-th loss : 3.1781e-02
tensor([[0.3090, 0.2212, 0.3791],
        [0.5355, 0.4180, 0.5487],
        [0.4649, 0.6204, 0.8141]], requires_grad=True)
5-th loss : 1.9226e-02
tensor([[0.2625, 0.2165, 0.3615],
        [0.5054, 0.4362, 0.5601],
        [0.5171, 0.6603, 0.8332]], requires_grad=True)
6-th loss : 1.1630e-02
tensor([[0.2264, 0.2128, 0.3478],
        [0.4819, 0.4504, 0.5689],
        [0.5578, 0.6913, 0.8480]], requires_grad=True)
7-th loss : 7.0356e-03
tensor([[0.1983, 0.2100, 0.3372],
        [0.4637, 0.4614, 0.5758],
        [0.5894, 0.7155, 0.8596]]