In [1]:
import torch
import torch.nn as nn

In [2]:
# 애초에 텐서를 gpu에서 생성하기
x = torch.cuda.FloatTensor(2,2)

x

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [3]:
# 텐서 생성 후 원하는 gpu에 옮기기
x = torch.FloatTensor(2,2)

x

tensor([[ 1.4013e-45,  0.0000e+00],
        [-1.4065e-02,  4.5916e-41]])

In [4]:
x.cuda()

tensor([[ 1.4013e-45,  0.0000e+00],
        [-1.4065e-02,  4.5916e-41]], device='cuda:0')

In [6]:
# 또는
d = torch.device('cuda:0')
x.cuda(device = d)# 얘는 복사 된 상태

tensor([[ 1.4013e-45,  0.0000e+00],
        [-1.4065e-02,  4.5916e-41]], device='cuda:0')

In [8]:
x.device # device가 cpu에 있음

device(type='cpu')

In [9]:
#다른 방법
x.to(device=d)

tensor([[ 1.4013e-45,  0.0000e+00],
        [-1.4065e-02,  4.5916e-41]], device='cuda:0')

In [11]:
x = torch.cuda.FloatTensor(2,2)

In [12]:
x = x.cpu()

In [13]:
d = torch.device('cpu')
x = x.to(d)

In [15]:
# Model을 gpu로 옮기기
linear = nn.Linear(2,2)

In [16]:
linear = linear.cpu()

In [17]:
d = torch.device('cuda:0')
linear = linear.to(d)

In [18]:
linear.device # 안됨!!!!!!

ModuleAttributeError: 'Linear' object has no attribute 'device'

In [22]:
# 그래서 쓰는 방법!
x = torch.cuda.FloatTensor(2,2)

In [23]:
x.new(2,2) # new를 써본다!!

tensor([[0.0000e+00, 4.7684e-06],
        [0.0000e+00, 1.1000e+00]], device='cuda:0')

In [24]:
list(linear.parameters())[0].new(2,2) # 이렇게 모델의 위치 파악도 가능!

tensor([[4.7684e-06, 1.1000e+00],
        [0.0000e+00, 1.1000e+00]], device='cuda:0')