In [2]:
import torch

In [4]:
W = torch.FloatTensor([[1,2],
                       [3,4],
                       [5,6]])
b = torch.FloatTensor([2,2])


In [5]:
def linear(x,W,b):
    y = torch.matmul(x,W) + b

In [7]:
x = torch.FloatTensor([[1,1,1]
                      ,[2,2,2]
                      ,[3,3,3]
                      ,[4,4,4]])
print(x.size())

torch.Size([4, 3])


In [8]:
y = linear(x,W,b)

In [14]:
import torch.nn as nn

In [15]:
class MyLinear(nn.Module):
    def __init__(self,input_dim = 3,output_dim = 2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        
        self.W = torch.FloatTensor(input_dim,output_dim)
        self.b = torch.FloatTensor(output_dim)
        
    def forward(self,x):
        # x_size -> (batch_size, input_dim)
        y = torch.matmul(x,self.W) + self.b
        # y_size -> (batch_size, input_dim) * (input_dim, output_dim)
        #    = (batch_size, output_dim)
        return y

In [16]:
linear = MyLinear(3,2)

y = linear(x) # linear.forward 라고 안해도 된대!

In [17]:
print(y.size())

torch.Size([4, 2])


In [18]:
for p in linear.parameters():  
# 실제로 학습을 시키려면 Parameter등록을 해야한다.
    print(p)

In [19]:
class MyLinear(nn.Module):
    def __init__(self,input_dim = 3,output_dim = 2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        
        self.W = nn.Parameter(torch.FloatTensor(input_dim,output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))
        
    def forward(self,x):
        # x_size -> (batch_size, input_dim)
        y = torch.matmul(x,self.W) + self.b
        # y_size -> (batch_size, input_dim) * (input_dim, output_dim)
        #    = (batch_size, output_dim)
        return y


In [23]:
linear = MyLinear(3,2)

y = linear(x)
print(y.size())

torch.Size([4, 2])


In [24]:
for p in linear.parameters(): #이제야 파라미터가 등록됨
    print(p)

Parameter containing:
tensor([[2.6330e+20, 3.4016e+21],
        [4.2491e-05, 6.8996e-07],
        [1.6913e+22, 1.0500e-08]], requires_grad=True)
Parameter containing:
tensor([4.3199e+24, 4.5909e-41], requires_grad=True)


In [25]:
linear = nn.Linear(3,2) # nn 모듈에서 제공해준다!
y = linear(x)

In [26]:
print(y.size())

torch.Size([4, 2])


In [27]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[ 0.4014, -0.3768, -0.0279],
        [-0.5136, -0.3214,  0.0241]], requires_grad=True)
Parameter containing:
tensor([-0.1927,  0.3188], requires_grad=True)


In [28]:
class MyLinear(nn.Module):
    def __init__(self,input_dim = 3,output_dim = 2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        
        self.linear = nn.Linear(input_dim,output_dim)
        # 이렇게 불러와도 된다 
    def forward(self,x):
        # x_size -> (batch_size, input_dim)
        y = self.linear(x)
        # y_size -> (batch_size, input_dim) * (input_dim, output_dim)
        #    = (batch_size, output_dim)
        return y