In [14]:
import numpy as np
print(np.__version__)

1.18.5


In [15]:
def pprint(arr):
    print("type : {}".format(type(arr)))
    print("shape : {}, dimention = {}, dtype = {}".format(arr.shape,arr.ndim,arr.dtype))
    print("Array's Data : \n",arr)

In [16]:
arr = [1,2,3]
a = np.array(arr)
pprint(a)

type : <class 'numpy.ndarray'>
shape : (3,), dimention = 1, dtype = int32
Array's Data : 
 [1 2 3]


In [17]:
arr = [(1,2,3),(11,12,13)]
a = np.array(arr,dtype = float)
pprint(a)

type : <class 'numpy.ndarray'>
shape : (2, 3), dimention = 2, dtype = float64
Array's Data : 
 [[ 1.  2.  3.]
 [11. 12. 13.]]


In [18]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
pprint(data)

type : <class 'numpy.ndarray'>
shape : (3, 2), dimention = 2, dtype = int32
Array's Data : 
 [[1 2]
 [3 4]
 [5 6]]


In [20]:
data = np.array([[1,2],[3,4]])
data[0,1]

2

In [21]:
data[1:3]

array([[3, 4]])

In [22]:
data[0:2,0]

array([1, 3])

In [23]:
arr = [[1,2,3],[4,5,6]],[[21,22,23],[24,25,26]]
a = np.array(arr,dtype = float)
pprint(a)

type : <class 'numpy.ndarray'>
shape : (2, 2, 3), dimention = 3, dtype = float64
Array's Data : 
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[21. 22. 23.]
  [24. 25. 26.]]]


In [24]:
data = np.array([1,2])
ones = np.array([1,1])
data+ones

array([2, 3])

In [25]:
data-ones

array([0, 1])

In [26]:
data*data

array([1, 4])

In [27]:
data/data

array([1., 1.])

In [29]:
data1 = np.array([3,9])
data2 = np.array([1,11])
data1 + data1*data2

array([  6, 108])

In [31]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12,],[1,2,3,4]])
unique_rows,indices,occurence_count = np.unique(a,axis = 0,return_counts = True,return_index = True)

print(unique_rows)

print(indices)

print(occurence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


In [32]:
a = np.array([7,10,7,4,4,6,2,1,5,2])

unique_values,indices_list = np.unique(a,return_index = True)

print(indices_list) # 1,2,4,5,6,7,10 이 배열에서 몇번째 index인지 알려준다. 

[7 6 3 8 5 0 1]
