In [2]:
import torch

In [3]:
x = torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [5]:
print(x[0])
print(x[0:])
print(x[0,:,:])

tensor([[1., 2.],
        [3., 4.]])
tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
tensor([[1., 2.],
        [3., 4.]])


In [6]:
print(x[:,0,:])

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


In [7]:
x = torch.FloatTensor(10,4)
splits = x.split(4,dim=0)
for s in splits:
    print(s.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [11]:
x = torch.FloatTensor(8,4)
chunks = x.chunk(3,dim=0)
for c in chunks:
    print(c.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


In [12]:
x = torch.FloatTensor([[[1,1],[2,2]],[[3,3],[4,4]],[[5,5],[6,6]]])
indice = torch.LongTensor([2,1])
print(x.size())

torch.Size([3, 2, 2])


In [15]:
y = x.index_select(dim=0,index = indice)
print(y)
print(y.size())

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])
torch.Size([2, 2, 2])


In [ ]:
# Useful Trick