In [1]:
import torch

In [2]:
x = torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [3]:
print(x.reshape(12))
print(x.reshape(-1)) # -1은 알아서 채워 같은 느낌인가

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [6]:
print(x.reshape(3,4))
print(x.reshape(3,-1)) # -1은 알아서 채워 같은 느낌인가
print(x.reshape(3,1,4))
print(x.reshape(-1,1,4))# -1은 알아서 채워 같은 느낌인가

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [7]:
print(x.reshape(3,2,2,1))

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


In [8]:
# squeeze : Remove dimension which has only one element

In [10]:
x = torch.FloatTensor([[[1,2],[3,4]]])
print(x.size())

torch.Size([1, 2, 2])


In [11]:
print(x.squeeze())
print(x.squeeze().size())

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


In [12]:
# 만약 one element인 부분이 없으면 변화 없음

In [13]:
# unsqueeze : Insert dimension at certain index

In [14]:
x = torch.FloatTensor([[1,2],[3,4]])
print(x.size())

torch.Size([2, 2])


In [15]:
print(x.unsqueeze(2))
print(x.unsqueeze(-1))
print(x.reshape(2,2,-1)) # 3개 다 같은 결과임!!

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
