In [1]:
import torch
import numpy

In [2]:
a = torch.FloatTensor([[1,2],[3,4]])
b = torch.FloatTensor([[2,3],[3,3]])

In [3]:
a+b

tensor([[3., 5.],
        [6., 7.]])

In [4]:
a-b

tensor([[-1., -1.],
        [ 0.,  1.]])

In [5]:
a*b

tensor([[ 2.,  6.],
        [ 9., 12.]])

In [6]:
a/b

tensor([[0.5000, 0.6667],
        [1.0000, 1.3333]])

In [7]:
a==b

tensor([[False, False],
        [ True, False]])

In [8]:
a!=b

tensor([[ True,  True],
        [False,  True]])

In [10]:
a**b    # b가 지수로 들어간다

tensor([[ 1.,  8.],
        [27., 64.]])

In [11]:
#Inplace Operations 
print(a)
print(a.mul(b)) # 새롭게 메모리 할당
print(a)
print(a.mul_(b))# a의 위치에 작성
print(a)
# 근데 메모리 측면에서 큰 차이는 없다고 한다.

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  6.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  6.],
        [ 9., 12.]])
tensor([[ 2.,  6.],
        [ 9., 12.]])


In [12]:
# Sum, Mean
x = torch.FloatTensor([[1,2],[3,4]])

In [13]:
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


In [15]:
print(x.sum(dim = 0)) # dim에 들어간 차원에 대해 제가하는 방향으로 눌러준다
print(x.sum(dim = -1)) # dim = 0 이면 height를 없애는 방향으로 

tensor([4., 6.])
tensor([3., 7.])


In [19]:
# Broadcast in Operations  
#Broadcast = 중계란 뜻이니까
# 일반적으로 tensor 연산은 size 가 맞아야 하는데
# 아닌 경우에도 연산이 되는 경우도 있음

SyntaxError: invalid syntax (<ipython-input-19-765efe7c45c1>, line 2)

In [16]:
x = torch.FloatTensor([[1,2],[4,8]])
y = torch.FloatTensor([3,5])
print(x.size())
print(y.size())

torch.Size([2, 2])
torch.Size([2])


In [17]:
z = x+y
print(z)
print(z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [18]:
x = torch.FloatTensor([[[1,2]]])
y = torch.FloatTensor([3,5])

print(x.size())
print(y.size())

torch.Size([1, 1, 2])
torch.Size([2])


In [20]:
# 위에서 볼 수 있듯이
# size가 2이면 더하기를 위해 [2] -> [1,1,2]로 맞춘 후 연산을 진행
# 이런게 BroadCast임

In [21]:
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([[3],[5]])
print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [22]:
z = x+y
print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


In [23]:
# Broadcast 사용시 의도치 않은 Broadcast 젹용 될 수 있다!!!