In [2]:
import torch

ft  = torch.FloatTensor([[1,2],[3,4]])

print(ft)

tensor([[1., 2.],
        [3., 4.]])


In [3]:
lt = torch.LongTensor([[1,2],[3,4]])
print(lt)

tensor([[1, 2],
        [3, 4]])


In [4]:
bt = torch.ByteTensor([[1,0],[0,1]])
print(bt)

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)


In [5]:
x = torch.FloatTensor(3,2)
print(x)

tensor([[0.0000e+00, 0.0000e+00],
        [1.8754e+28, 2.5382e-09],
        [5.4128e+22, 1.0015e-11]])


In [6]:
import numpy as np

In [7]:
x = np.array([[1,2],[3,4]])
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [8]:
x = torch.from_numpy(x) #important!!
print(x,type(x))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>


In [9]:
x = torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(x.size())  # size는 괄호 필수
print(x.shape)   # shape는 괄호 없음 -> []사용

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [10]:
print(x.dim())

3


In [11]:
print(x.size(-1))
print(x.shape[-1])

2
2
