In [2]:
import torch

In [4]:
x = torch.FloatTensor([[1,2]
                      ,[3,4]]).requires_grad_(True)

In [5]:
x1 = x+2
x2 = x-2
x3 = x1*x2
y = x3.sum()

print(x1)
print(x2)
print(x3)
print(y)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)
tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)
tensor(14., grad_fn=<SumBackward0>)


In [6]:
y.backward() # y는 스칼라여아 backward 사용가능

In [7]:
print(x.grad)

tensor([[2., 4.],
        [6., 8.]])


In [9]:
x3.detach_().numpy()

array([[-3.,  0.],
       [ 5., 12.]], dtype=float32)